# Generated by Django 2.0.3 on 2018-03-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_book_instance'),
        ('ecommerce', '0004_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
