# Generated by Django 2.0.3 on 2018-04-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20180402_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
